---
driver:
  name: vagrant
  customize:
    cableconnected1: "on"

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
    attributes:
